### PR TITLE
Advanced JAR picking

### PR DESCRIPTION
**Pull request by GhostFace54**
In-depth info about JARs from my experience.

### CODE REVIEW

**Comment by Kruemmelspalter** [comment]
It's not a markdown file, please append `.md` to the filename

**Comment by GhostFace54** [comment]
Done, I have never made a pull request before so I'll have to get used to it a little

**Comment by JustDoom** [comment]
This is amazing! Thank you very much. I'll merge tonorrow or later tonight

**Comment by JustDoom** [comment]
Decided to do it now as it simply adds a new file

**Pull request merged**
