### PR TITLE
Added linting and locale

### PR DESCRIPTION
**Pull request by mbround18**
# Linting and Locale

After reading your post on Reddit, I would like to contribute. Think of this PR as a suggestion given the scope of this repository and I hope to add more content in the future! 

## Contributions

- Added prettier + markdownlint
- Added Husky for pre-commit hook
- Fixed and linted the markdown files
- Moved files into an `en_us` based path
- Added some vscode configs. 
- Added relative path for local markdown files.

### CODE REVIEW

**Comment by Kruemmelspalter** [comment]
I would exclude your VSC settings (the .vscode directory)

**Comment by Kruemmelspalter** [comment]
And please merge the current main into yours so you lint the most recent version

**Comment by JustDoom** [comment]
ill merge if you update to latest

**Comment by mbround18** [comment]
Merged upstream main into branch and removed `.vscode` config. Although, you might want to add an `.edtorconfig` or similar to ensure common code styling and file endings.

**Comment by Kruemmelspalter** [comment]
Was the en_us automatical or can I just manually add a directory `de_de` to translate to German?

**Pull request merged**
