### PR TITLE
How to make an RPi MC server

### PR DESCRIPTION
**Pull request by timof121**

### CODE REVIEW

**Comment by GhostFace54** [comment]
Interesting thing! I've never heard of this but could you try fixing the grammatical errors?

**Comment by timof121** [comment]
> Interesting thing! I've never heard of this but could you try fixing the grammatical errors?

Oh ok

**Comment by Vincent-Br** [comment]
maybe a bit more detail about changing ram amount and server version?

**Comment by timof121** [comment]
> maybe a bit more detail about changing ram amount and server version?

Ok i will look into this later bc i need to go to school rn

**Comment by omit01** [comment]
I would recommand against hosting a server on a RPi, as the later versions of Minecraft are really dependent on CPU. Thereby you will see TPS-loss quickly. Maybe it's an idea to add this to the guide.

**Comment by timof121** [comment]
> I would recommand against hosting a server on a RPi, as the later versions of Minecraft are really dependent on CPU. Thereby you will see TPS-loss quickly. Maybe it's an idea to add this to the guide.

Hmmm i think the Pi 4 isn’t that bad at CPU because i was hosting a school SMP on a 8GB Pi with 10~ stable players and it was running at 19.50-20 TPS

**Comment by timof121** [comment]
> maybe a bit more detail about changing ram amount and server version?

Done

**Pull request merged**
